<a href="https://colab.research.google.com/github/michalis0/Business-Intelligence-and-Analytics/blob/master/labs/03%20-%20Pandas%20and%20Python/walkthroughs/walkthrough_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align="center"> Walkthrough - Lab 3</h1>

<div>
<td>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Logo_Universit%C3%A9_de_Lausanne.svg/2000px-Logo_Universit%C3%A9_de_Lausanne.svg.png" style="padding-right:10px;width:240px;float:left"/></td>
<h2 style="white-space: nowrap">Business Intelligence and Analytics</h2></td>
<hr style="clear:both">
<p style="font-size:0.85em; margin:2px; text-align:justify">

</div>

# Basic Pandas operations

**Goal**: Our goal here is to learn how to load a dataset into a Pandas DataFrame. The dataset can come either in CSV or in JSON format. We will see also how to perform basic data manipulations and very basic data visualizations so that you understand the nature of your data.

## 1. Loading a dataset in CSV format

First you have to import the `pandas` package.

In [1]:
import pandas as pd # Press shift+enter to execute it

Now you can see that you autocomplete your code with functions that are included in `pandas`. E.g. type `pd.read` and you'll see that it recommends some relevant functions:

In [2]:
# Let's load a file
url = "https://media.githubusercontent.com/media/michalis0/Business-Intelligence-and-Analytics/master/data/pandas_tutorial_read.csv"
data = pd.read_csv(url)
data.head()

  01.01.2018 00:01;read;country_7;2458151261;SEO;North America
0  01.01.2018 00:03;read;country_7;2458151262;SEO...
1  01.01.2018 00:04;read;country_7;2458151263;AdW...
2  01.01.2018 00:04;read;country_7;2458151264;AdW...
3  01.01.2018 00:05;read;country_8;2458151265;Red...
4  01.01.2018 00:05;read;country_6;2458151266;Red...

Is the above correct? Most likely not.

CSV stands for "Comma Separated Values", which is not the case here. We see there are ';' and the data seems to be in one column. The default delimiter is ',' so we need to change it.

In [3]:
data = pd.read_csv(url, delimiter=';')
data.head()

   01.01.2018 00:01  read  country_7  2458151261      SEO  North America
0  01.01.2018 00:03  read  country_7  2458151262      SEO  South America
1  01.01.2018 00:04  read  country_7  2458151263  AdWords         Africa
2  01.01.2018 00:04  read  country_7  2458151264  AdWords         Europe
3  01.01.2018 00:05  read  country_8  2458151265   Reddit  North America
4  01.01.2018 00:05  read  country_6  2458151266   Reddit  North America

This looks better. But something else does not look good now. Our DataFrame is missing a header, let's assign one:

In [4]:
data = pd.read_csv(url,
                   delimiter=';',
                   names = ['my_datetime', 'event', 'country', 'user_id', 'source', 'topic'])
data.head()

        my_datetime event    country     user_id   source          topic
0  01.01.2018 00:01  read  country_7  2458151261      SEO  North America
1  01.01.2018 00:03  read  country_7  2458151262      SEO  South America
2  01.01.2018 00:04  read  country_7  2458151263  AdWords         Africa
3  01.01.2018 00:04  read  country_7  2458151264  AdWords         Europe
4  01.01.2018 00:05  read  country_8  2458151265   Reddit  North America

With the `head` function you see the first few lines. The `.shape` function shows the shape of the dataframe (rows, columns). You can also see the:

- whole dataset: just type ```data```
- the beginning as before ```data.head()```
- the last 5 entries ```data.tail()``` or
- a sample such as ```data.sample(5)```
- some descriptive statistics ```data.describe()```
Try it out below:

In [5]:
data.shape

(1795, 6)

In [6]:
# Use this cell to write your own code

### DataFrame components
There are three components of the DataFrame: the index, columns and data (values). We can extract each of these components into their own variables. Let's do that and then inspect them:

In [7]:
index = data.index
columns = data.columns
values = data.values

In [8]:
index

RangeIndex(start=0, stop=1795, step=1)

In [9]:
columns

Index(['my_datetime', 'event', 'country', 'user_id', 'source', 'topic'], dtype='object')

In [10]:
values

array([['01.01.2018 00:01', 'read', 'country_7', '2458151261', 'SEO',
        'North America'],
       ['01.01.2018 00:03', 'read', 'country_7', '2458151262', 'SEO',
        'South America'],
       ['01.01.2018 00:04', 'read', 'country_7', '2458151263', 'AdWords',
        'Africa'],
       ...,
       ['01.01.2018 23:59', 'read', 'country_6', '2458153053', 'Reddit',
        'Asia'],
       ['01.01.2018 23:59', 'read', 'country_7', '2458153054', 'AdWords',
        'Europe'],
       ['01.01.2018 23:59', 'read', 'country_5', '2458153055', 'Reddit',
        'Asia']], dtype=object)

### Data types of the components

In [11]:
type(index)

pandas.core.indexes.range.RangeIndex

In [12]:
type(columns)

pandas.core.indexes.base.Index

In [13]:
type(values)

numpy.ndarray


The index and the columns are the same type: a pandas **`Index`** object (**`RangeIndex`** is of type **`Index`**), which is a sequence of labels for either the rows or the columns.

The values are a NumPy **`ndarray`**, which stands for n-dimensional array, and is the primary container of data in the NumPy library. Pandas is built directly on top of NumPy.

### Selecting columns

If you want to select two particular columns you can do it like this:

```data[['country', 'user_id']]```

or you can take the columns in a different order:

```data[['user_id', 'country']]```.

The way to remember the syntax is that outer brackets signify that you want to select columns, and the inner brackets are for the list itself.

Try it out.

In [14]:
data[['user_id', 'country']]

         user_id    country
0     2458151261  country_7
1     2458151262  country_7
2     2458151263  country_7
3     2458151264  country_7
4     2458151265  country_8
...          ...        ...
1790  2458153051  country_2
1791  2458153052  country_8
1792  2458153053  country_6
1793  2458153054  country_7
1794  2458153055  country_5

[1795 rows x 2 columns]

The above returns a pandas.DataFrame. If you want to return a pandas.Series instead then you can use this syntax:

```data.user_id ```

or

``` data['user_id'] ```

In [15]:
data.user_id

0       2458151261
1       2458151262
2       2458151263
3       2458151264
4       2458151265
           ...
1790    2458153051
1791    2458153052
1792    2458153053
1793    2458153054
1794    2458153055
Name: user_id, Length: 1795, dtype: object

If you want to filter one those users that came from SEO then you can write:

``` data[data.source == 'SEO'] ```

where the inner statement will create a boolean mask.

In [16]:
data[data.source == 'SEO']

           my_datetime event    country     user_id source          topic
0     01.01.2018 00:01  read  country_7  2458151261    SEO  North America
1     01.01.2018 00:03  read  country_7  2458151262    SEO  South America
11    01.01.2018 00:08  read  country_7  2458151272    SEO      Australia
15    01.01.2018 00:11  read  country_7  2458151276    SEO  North America
16    01.01.2018 00:13  read  country_8  2458151277    SEO  North America
...                ...   ...        ...         ...    ...            ...
1772  01.01.2018 23:45  read  country_7  2458153033    SEO  South America
1777  01.01.2018 23:49  read  country_5  2458153038    SEO  North America
1779  01.01.2018 23:51  read  country_4  2458153040    SEO  South America
1784  01.01.2018 23:54  read  country_2  2458153045    SEO  North America
1791  01.01.2018 23:58  read  country_8  2458153052    SEO           Asia

[346 rows x 6 columns]

### Chaining

You can combine multiple selection methods as follows:

``` data.head()[['country', 'user_id']] ```

**CAUTION**: A thing to keep in mind is that when you use chaining you work on *copies* of the original DataFrame. So if you use chaining to change data, you may observe that the original DataFrame was not changed.

#### Exercice 1:
Now it's your turn to solve an exercise and deepen your knowledge.

Select the user_id, the country and the topic columns for the users who are from country_2 and show only the first 10 results.

In [ ]:
# Enter your solution here.

In [18]:
# Solution
# data[['user_id', 'topic', 'country']][data['country'] == 'country_2'].head(10)

### Column Types

Remember that each column/attribute of our data may have different attribute types. Have a look at the following table to understand the different DataTypes in Pandas and Python.

| Pandas dtype  | Python type  | NumPy type|Usage
| :--- | :--- | :--- | :--- |
| object| str or mixed | string_, unicode_, mixed types| Text or mixed numeric and non_numeric values |
| int 64| int| int_, int8, int16, int32, int64, uint8, uint18, uint32, uint64 | Integer numbers i.e. [1,2,3,...] |
| float64| float| float_, float15, float32, float64 | Floating point numbers (They contain decimal points) |
| bool| bool|bool_| True/False values|
| datetime64 | NA | datetime64[ns]     | Date and time values  |
| timedelta[ns] | NA  | NA| Differences between two datetime|
| category | NA| NA| Finite list of text values|

Although Pandas will correctly infer the type of data most of the times, it is important to check our columns and convert them if needed. Otherwise our results might get messed up.

The function `.dtypes` allows us to see the type of each column. Run the following cell to see how it works:

In [19]:
data.dtypes

my_datetime    object
event          object
country        object
user_id        object
source         object
topic          object
dtype: object

We can see that although most columns seem to have the correct type, we can still improve our DataFrame. Let's convert the ["my_datetime"] column to the "datetime64" type, so that Pandas knows this column contains Date and Time values.

For this, the [.to_datetime()](https://https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html) function might come in handy.

In [20]:
# First, let's convert the column type
data["my_datetime"] = pd.to_datetime(data["my_datetime"])

# Now let's have a look at the dtypes once again
data.dtypes

my_datetime    datetime64[ns]
event                  object
country                object
user_id                object
source                 object
topic                  object
dtype: object

The user_id column seems to contain integers. Pandas did not correctly infer it since some of the rows in this column are corrupted (they contain other values than integers).

However, we can still use the `pd.to_numeric` function to convert the column to the correct type. We can use the `errors = 'coerce'` argument to handle these errors. This will set all cells in the ["user_id"] column containing corrupted entries to NaN (Not a Number).

Other possible values for "errors=" are:
 * `errors = raise` This will raise an error if it encounters an invalid entry.
 * `errors = ignore` This will return the original data (the data we passed as an argument) if it encounters an error. No conversion will take place.

In [21]:
# Let's convert the column type
data["user_id"] = pd.to_numeric(data["user_id"], errors='coerce')

# Now let's have a look at the dtypes once again
data.dtypes

my_datetime    datetime64[ns]
event                  object
country                object
user_id               float64
source                 object
topic                  object
dtype: object

Since the number of possible countries is limited, we can convert that column to the categorical type with the `.astype()` function:

In [22]:
# Change dtype
data['country'] = data['country'].astype('category')

# Now let's have a look at the dtypes once again
data.dtypes

my_datetime    datetime64[ns]
event                  object
country              category
user_id               float64
source                 object
topic                  object
dtype: object

### Dropping missing values

Since our columns contained some corrupted data, those cells were set to NaN.
The function `.isnull()` will return a DataFrame with values:
 * False for cells where the data is not null
 * True for cells where the data is null

We can then use `.sum()` to sum all values where the latter is True.

In [23]:
# Let's see how many column values are missing
data.isnull().sum()

my_datetime    0
event          0
country        0
user_id        4
source         0
topic          0
dtype: int64

We can now remove the missing values with the `.dropna()` function.
If no argument is passed, this function will drop all rows where at least one of the values is missing.

In [24]:
# We first drop all the rows where at least one of the values is missing
data = data.dropna()

# Let's have another look
data.isnull().sum()

my_datetime    0
event          0
country        0
user_id        0
source         0
topic          0
dtype: int64

---
## 2. Loading JSON files

Many of the data in the Internet exists in JSON format which is a structured text format, and is very similar to a Python dictionary.

We will see how to load a JSON dataset in a Pandas DataFrame.

We will use the Citibike API that provides a real-time view of the Citibike stations in New York.
The API call at http://www.citibikenyc.com/stations/json.

In [25]:
# Import libraries
import pandas as pd

# Display all columns
pd.set_option('display.max_columns', None)
# Display max 50 rows
pd.set_option('display.max_rows', 50)

In [26]:
# Read json file

# Import urllib library
from urllib.request import urlopen

# Import json
import json
# Store the URL in url as
# parameter for urlopen
url = "https://raw.githubusercontent.com/michalis0/Business-Intelligence-and-Analytics/Editing/data/station_status/station_status.json"

# Store the response of URL
response = urlopen(url)

# Store the JSON response
# from url in data
data = json.loads(response.read())

# Uncomment to see how the data looks:
# print(data)

In [27]:
# Below you see how the JSON file looks. The JSON results contain two keys:
#  - The 'data' key contains all the data
#  - The 'last_updated' key contains the timestamp of the last update
#  - And the 'ttl' key contains the time to live of the data
data.keys()

dict_keys(['data', 'last_updated', 'ttl'])

In [28]:
# The field "data" contains the information we want but it has a nested structure
data["data"].keys()
# The field "stations" contains the actual data

dict_keys(['stations'])

In [29]:
# We can convert the nested dictionary to a pandas dataframe
# We want to extract the data from the key "data"
df_info = pd.DataFrame(data["data"]["stations"])
df_info.sample(5)

,is_renting,eightd_has_available_keys,station_status,is_installed,num_docks_disabled,num_scooters_available,legacy_id,num_docks_available,num_bikes_available,is_returning,station_id,last_reported,num_scooters_unavailable,num_bikes_disabled,num_ebikes_available,valet,eightd_active_station_services
277,1,False,active,1,0,0.0,529,28,9,1,66dc85bb-0aca-11e7-82f6-3863bb44ef7c,1677705290,0.0,4,4,NaN,NaN
351,1,False,active,1,0,0.0,3763,0,27,1,9b721468-3b28-429d-9e13-580cdf00a6a4,1677705305,0.0,0,1,NaN,NaN
535,1,False,active,1,0,0.0,250,3,56,1,66db40ef-0aca-11e7-82f6-3863bb44ef7c,1677705311,0.0,1,13,NaN,NaN
1870,1,False,active,1,0,NaN,5052,11,6,1,5052,1677699950,NaN,2,6,NaN,NaN
1112,1,False,active,1,0,NaN,4128,20,4,1,4128,1677705011,NaN,0,2,NaN,NaN

In [30]:
# Display types of each column
df_info.dtypes

is_renting                          int64
eightd_has_available_keys            bool
station_status                     object
is_installed                        int64
num_docks_disabled                  int64
num_scooters_available            float64
legacy_id                          object
num_docks_available                 int64
num_bikes_available                 int64
is_returning                        int64
station_id                         object
last_reported                       int64
num_scooters_unavailable          float64
num_bikes_disabled                  int64
num_ebikes_available                int64
valet                              object
eightd_active_station_services     object
dtype: object

In [31]:
# Replace NAN value of all integer fields by 0
df_info.fillna(0, inplace=True)

## Grouping values by feature

Sometimes if you want to get an indicator (e.g. mean, max, min...) of the data on one particular value of a feature, you will first need to group values in relation to the values of that feature. To do so, we use a function in the Pandas library, `groupby()`. Let's say for example that we want to know the mean of available bikes at the renting stations (is_renting = 1). We have to group values in function of this feature.

In [33]:
# Take the mean of bikes available for renting stations (is_renting = 1) and non-renting stations (is_renting = 0)
df_info_mean = df_info.groupby('is_renting')['num_bikes_available'].mean()
df_info_mean.head()

is_renting
0     3.432432
1    13.201830
Name: num_bikes_available, dtype: float64

---
For the following questions, you may find useful to use the following functions:
- `describe()`,
- `mean()`,
- `groupby()`,
- `where()`,
- `sort_values()`

You will find more information about them on the offcial documentation.

__Question 2.1:__ Add a column named `ebike_prop` which contains the proportion of available e-bikes among all available bikes. That is we want the following ratio expressed in percenatge : $$\frac{num \ ebikes \ available}{num \ ebikes \ available + num \ bikes \ available}$$

In [34]:
# Add column with the proportion of e-bikes available
df_info["ebike_prop"] = df_info["num_ebikes_available"] / (df_info["num_ebikes_available"] + df_info["num_bikes_available"]) * 100
df_info.head()

,is_renting,eightd_has_available_keys,station_status,is_installed,num_docks_disabled,num_scooters_available,legacy_id,num_docks_available,num_bikes_available,is_returning,station_id,last_reported,num_scooters_unavailable,num_bikes_disabled,num_ebikes_available,valet,eightd_active_station_services,ebike_prop
0,1,False,active,1,0,0.0,3092,1,25,1,66dd01c5-0aca-11e7-82f6-3863bb44ef7c,1677705200,0.0,1,9,0,0,26.470588
1,1,False,active,1,0,0.0,432,33,5,1,66dc10d1-0aca-11e7-82f6-3863bb44ef7c,1677705201,0.0,6,0,0,0,0.000000
2,1,False,active,1,0,0.0,3169,69,5,1,66dd4ec7-0aca-11e7-82f6-3863bb44ef7c,1677705197,0.0,0,5,0,0,50.000000
3,1,False,active,1,0,0.0,3115,5,43,1,66dd2060-0aca-11e7-82f6-3863bb44ef7c,1677705198,0.0,0,0,0,0,0.000000
4,1,False,active,1,0,0.0,3891,13,7,1,b35ba3c0-d3e8-4b1a-b63b-73a7bb518c9e,1677705198,0.0,0,0,0,0,0.000000

__Question 2.2:__ What are the `station_id` of the stations with the greatest proportion of available e-bikes ? Display the first 5 stations.

In [35]:
df_info.sort_values(by="ebike_prop", ascending=False)[["station_id", "ebike_prop", "num_docks_available", "num_ebikes_available", "num_bikes_available"]].head(5)

,station_id,ebike_prop,num_docks_available,num_ebikes_available,num_bikes_available
1894,5082,50.0,66,1,1
114,6fd61eee-d0ef-4580-9704-bd06b82bcb61,50.0,23,9,9
1197,4227,50.0,14,1,1
1199,4229,50.0,21,1,1
1203,4235,50.0,51,4,4

__Question 2.3:__ What are the `station_id` of the stations with the greatest proportion of available e-bikes where the number of available e-bikes is greater or equal to 10 (so that you can maximize your chances to get an e-bike by the time you reach the station) ? Display the first 10 stations id with the proportion, number of docks of the station and the number of bikes available.

In [36]:
df_temp = df_info.sort_values(by="ebike_prop", ascending=False)[["station_id", "ebike_prop", "num_docks_available", "num_ebikes_available", "num_bikes_available"]]
df_temp[df_temp["num_ebikes_available"] >= 10].head(10)

,station_id,ebike_prop,num_docks_available,num_ebikes_available,num_bikes_available
1418,4487,50.000000,2,12,12
314,2436e886-dc53-47cb-8733-d663f9dcd922,50.000000,10,10,10
960,fadf00cf-d84a-49e8-9607-c67154915412,50.000000,4,22,22
166,1b00fb53-da32-4b14-9a9a-84a391c8951c,50.000000,18,11,11
970,655b0878-c22b-4f8c-8675-21bf30d1eebf,47.826087,4,11,12
993,5faf99b8-9046-450f-9d2a-d13279b3d016,47.619048,20,10,11
978,66dd8b48-0aca-11e7-82f6-3863bb44ef7c,47.619048,7,10,11
338,66dc3f08-0aca-11e7-82f6-3863bb44ef7c,47.008547,5,55,62
1065,4073,46.666667,11,21,24
440,66dc21d4-0aca-11e7-82f6-3863bb44ef7c,45.714286,10,32,38

__Question 2.4:__ It is often interesting to find simple statistics about a column like the mean, or the highest values. What is the proportion of stations with a proportion of available e-bikes >= 50% ? Same question for a proportion of 75%.

In [37]:
# Display the statistics of the initial data file for the newly_created column "ebike_prop"
df_info["ebike_prop"].describe()

count    1717.000000
mean       16.089948
std        16.773704
min         0.000000
25%         0.000000
50%        10.526316
75%        29.629630
max        50.000000
Name: ebike_prop, dtype: float64

__Question 2.5:__ Print the number of disabled bikes in the entire network.

In [38]:
df_info["num_bikes_disabled"].sum()

2179

__Question 2.6:__ Count the number of stations with at least 5 bikes unavailable. Display the following fields:
- station_id,
- station_status,
- num_bikes_available,
- num_docks_available,
- num_bikes_disabled

In [39]:
# Number of stations with more than 5 disabled bikes
print(df_info[df_info["num_bikes_disabled"] > 5].shape[0])

df_info[df_info["num_bikes_disabled"] > 5][["station_id", "station_status", "num_bikes_available", "num_docks_available", "num_bikes_disabled"]]

32

,station_id,station_status,num_bikes_available,num_docks_available,num_bikes_disabled
1,66dc10d1-0aca-11e7-82f6-3863bb44ef7c,active,5,33,6
17,66dc8a3d-0aca-11e7-82f6-3863bb44ef7c,active,14,59,6
37,457ea5d7-d643-4028-87db-46dee0b81555,active,5,12,8
62,66de85d2-0aca-11e7-82f6-3863bb44ef7c,active,29,10,6
94,66dbe571-0aca-11e7-82f6-3863bb44ef7c,active,51,1,7
162,66dc7773-0aca-11e7-82f6-3863bb44ef7c,active,24,11,9
164,66dd17a5-0aca-11e7-82f6-3863bb44ef7c,active,24,9,18
200,66db65aa-0aca-11e7-82f6-3863bb44ef7c,active,68,14,9
318,66dc48ef-0aca-11e7-82f6-3863bb44ef7c,active,53,9,6
342,66dc8768-0aca-11e7-82f6-3863bb44ef7c,active,27,9,6
357,b30815c0-99b6-451b-be15-902992cb8abb,active,52,3,6
366,66ddbd20-0aca-11e7-82f6-3863bb44ef7c,active,10,0,9
497,66dd2208-0aca-11e7-82f6-3863bb44ef7c,active,16,20,6
511,66dc2238-0aca-11e7-82f6-3863bb44ef7c,active,8,64,6
550,66db2fd0-0aca-11e7-82f6-3863bb44ef7c,active,23,4,6
552,66dc192f-0aca-11e7-82f6-3863bb44ef7c,active,0,16,7
563,b94d0241-bce7-44a9-ab1c-ece0740a4134,active,6,7,6
620,581d8683-c217-4f96-89cb-b5a94d780b83,active,47,24,6
665,cae4f2f4-9642-474c-95cc-6cc07592f120,active,29,2,6
697,66dbe4db-0aca-11e7-82f6-3863bb44ef7c,active,39,0,7
796,66ddd545-0aca-11e7-82f6-3863bb44ef7c,active,74,6,7
811,66db3e32-0aca-11e7-82f6-3863bb44ef7c,active,34,6,6
886,93e2e1a5-49c5-41f8-a6bf-b399b6a5140d,active,13,49,6
911,66dc7802-0aca-11e7-82f6-3863bb44ef7c,active,7,40,7
915,e36b5913-8e46-4c2a-b9be-73bdf8ee548b,active,6,43,6
1128,4144,active,0,0,15
1247,4285,active,0,16,8
1452,4550,active,12,5,6
1504,4611,active,0,0,19
1685,4831,active,1,20,6
1819,4998,active,1,10,7
1889,5075,active,1,2,19

---
## Writing the data to a CSV

With the above, we just scratched the surface of what it means to do data processing.

After you did your basic data processing, you may want to save the DataFrame in a new CSV file, so that you don't have to repeat the same pre-processing everytime. You can use the [to_csv](https://datatofish.com/export-dataframe-to-csv/) function.

**Note**: When you use Google Colab, this file will only be saved in your temporary virtual machine space and will be deleted once your Colab instance is closed (i.e. you close the window). If you want to explore more permanent solutions of saving your file look [here](https://colab.research.google.com/notebooks/io.ipynb).

In [40]:
# Uncomment the following to save the file
# df_info.to_csv("my_new_file.csv", sep=",")